### PR TITLE
update socrata uid for the doitt_buildingfootprints_historical.yml 

### PR DESCRIPTION
**Pull request by mbh329**
need to match uid to open data url

### CODE REVIEW

**Review by SashaWeinstein — APPROVED** [review]
This looks good as long as you tested it by writing to digital ocean and making sure the file was correct

**Review by AmandaDoyle — APPROVED** [review]

**Comment by AmandaDoyle** [comment]
I think that updating the uid to `ipkp-snf6` will resolve this issue.
We want the geojson for the polygons and the url for that dataset is:
https://data.cityofnewyork.us/api/geospatial/ipkp-snf6?method=export&format=GeoJSON

**Comment by SashaWeinstein** [comment]
Amazing! Did you test this out? Should I?
What's the difference between `historic_buildings` and `historic_buildings_p`? How did you know we wanted a specific layer and how did you know what layer we wanted?

**Comment by mbh329** [comment]
Great - would be nice to talk this through. I can test it if you haven't already sasha

**Comment by SashaWeinstein** [comment]
Sure, that would be great thanks Max

**Review by AmandaDoyle — APPROVED** [review]

**Comment by SashaWeinstein** [comment]
🎉 🎊  so glad to put this one behind us lol

**Pull request merged**
