### PR TITLE
Update `dcp_atomicpolygons`

### PR DESCRIPTION
**Pull request by mbh329**
One reviewer required. Addresses issue #274 and one task in #272.

Update the url path to reflect change in the Bytes of the Big Apple server. 

Test by running the dataset locally.

### CODE REVIEW

**Comment by td928** [comment]
tested with 22c has success. Is this the only version we need to test for now?

**Review by td928 — APPROVED** [review]
22c worked lgtm

**Comment by mbh329** [comment]
I haven't tested any of the older versions but might be good to double check if we can do that

**Comment by mbh329** [comment]
@td928 FYI I tested 22b and it doesn't work

**Pull request merged**
