### PR TITLE
WIP - update poetry installation method so CI still works

### PR DESCRIPTION
**Pull request by SPTKL**
according to error message in CI 
```console
This installer is deprecated, and scheduled for removal from the Poetry repository on or after January 1, 2023.
See https://github.com/python-poetry/poetry/issues/6377 for details.

You should migrate to https://install.python-poetry.org/ instead, which supports all versions of Poetry, and allows for `self update` of versions 1.1.7 or newer.
Instructions are available at https://python-poetry.org/docs/#installation.

Without an explicit version, this installer will attempt to install the latest version of Poetry.
This installer cannot install Poetry 1.2.0a1 or newer (and installs will be unable to `self update` to 1.2.0a1 or newer).

To continue to use this deprecated installer, you must specify an explicit version with --version <version> or POETRY_VERSION=<version>.
Alternatively, if you wish to force this deprecated installer to use the latest installable release, set GET_POETRY_IGNORE_DEPRECATION=1.

Version 1.3.1 is not supported by this installer! Please specify a version prior to 1.2.0a1 to continue!
```

previous installation method is deprecated by poetry

### CODE REVIEW

**Comment by mbh329** [comment]
Hey @SPTKL - good to hear from you and thanks for keeping up with this! We flagged this in an issue #326  a few weeks back and am in the process of updating the poetry installation for a bunch of our products.  I tested this PR on a new feature branch but the pytest workflow is still failing. I've been trying to get this updated as well but seem to be running into issues with the poetry path in the devcontainer.

**Comment by mbh329** [comment]
@SPTKL see PR https://github.com/NYCPlanning/db-data-library/pull/351/files and this PR https://github.com/NYCPlanning/db-gru-qaqc/pull/211/files - I think @td928 figured this out. The change in the path from one installation from the next was tougher to debug than we initially thought and we also hadn't been addressing poetry maintenance as much as we should have

**Comment by SPTKL** [comment]
nice glad you figured it out, also fyi, you should look into pipx, it might be a better tool for this purpose

**Review by damonmcc — APPROVED** [review]
approving and merging. @mbh329 fixes in https://github.com/NYCPlanning/db-data-library/pull/366 effectively implemented changes here. changes in this PR are now slight improvements on it (e.g. pinning `poetry` version)

edit: or not. [tests failed](https://github.com/SPTKL/db-data-library/actions/runs/4126161946/jobs/7127709052) in SPTKL's remote repo due to `peotry` version in lock file not being 1.1.6

**Comment by damonmcc** [comment]
closing in favor of https://github.com/NYCPlanning/db-data-library/pull/368

**Pull request closed without merging**
