### PR TITLE
Update `dsny_textiledrop`

### PR DESCRIPTION
**Pull request by SashaWeinstein**
Simple change, new and old source data are both on socrata

### CODE REVIEW

**Review by mbh329 — COMMENTED** [review]
The latest data in digital ocean is updated with the new donations dataset dsny sent over so this change looks good. My question is that if this dataset is fundamentally different than what we previously received for dsny_textiledrop and the filtering to textile drop sites isn't done in the data library (but in facdb), do we still call this dsny_textiledrop? @AmandaDoyle @SashaWeinstein @td928

**Comment by SashaWeinstein** [comment]
This is a good question, it's a little confusing to upload the whole donations dataset as textile drop. I'm not sure what a better approach would be though. 
We could write the donations data to a new dataset in data library, then download it and filter for textile dropoffs. However this would break the pattern of each source data in facdb coming from exactly one data library dataset. 
Alternatively we could do the filtering in data library, but that's more processing than we usually do

**Comment by AmandaDoyle** [comment]
I agree that having the new DSNY donations dataset map to `dsny_textiledrop` as is is confusing.  I propose we have this new dataset be called `dsny_donatenycdirectory` and then pull `dsny_donatenycdirectory` into FacDB and filter it in FacDB to just get clothing donation drop off sites.  This still keeps one DSNY facsubgroup coming from a single source dataset, but there are other examples of one source dataset populating many different facility types in FacDB.  @SashaWeinstein  Happy to chat live to better understand how you think that this approach would break the pattern of each source data in facdb coming from exactly one data library dataset.

**Comment by SashaWeinstein** [comment]
Oh ok neat. What I'm worried about with the data library/source dataset pattern break is the donate nyc dataset has other dropoff types like electronics and food that currently have their own datasets in data library. Thinking ahead, would we collapse these 3 data sources down to one? Think that's the "right" way but it seems like a lot of work for input datasets that can change for each build.

**Comment by AmandaDoyle** [comment]
@SashaWeinstein Maybe we take 10min to talk this through.  It's my understanding that this new dataset reports donation sites and not disposal sites.  For example `dsny_donatenycdirectory` reports where you can donate food, but `dsny_fooddrop` reports composting and food scrap drop off locations.  Therefore, the other DSNY source datasets would not be replaced with this new dataset.  Sam also confirms this in his email.

**Comment by SashaWeinstein** [comment]
Oh ok great. Which email? And what about electronics drop-offs, does that overlap?

**Comment by SashaWeinstein** [comment]
I looked at the electronic drop-off sites in the donations dataset and they are all places I've never heard of, whereas locations in `dsny_electronicsdrop` are all chain technology retailers like apple or best buy. So no bigger change needed. I reverted the textile drop back to how it was, replacing latest with the original data. I also added the donations data to a new dataset and uploaded a .sql file ready for facdb to pull

**Review by td928 — APPROVED** [review]

**Review by mbh329 — APPROVED** [review]
Tested locally and the template works as expected with populated sql and csv files

**Review by abrieff — APPROVED** [review]
tested locally, I am able to output in csv, geojson, shapefile

**Review by Oysters1874 — APPROVED** [review]
tested locally and it worked on my machine

**Comment by td928** [comment]
also tagging #246 so we will know to close off the issue once merged in

**Pull request merged**
