### PR TITLE
Automate pushing new image

### PR DESCRIPTION
**Pull request by SashaWeinstein**
Small PR, one reviewer 🐳 
There are several advantages to putting this process in a workflow. 
 - It's helpful documentation to help another engineer understand our proccess 
 - Links an image to it's last github commit 
 - Speeds up deploying changes to the action
I think in general our process should be to push changes to the image when possible and not change the library action archive repo if we can avoid it

### CODE REVIEW

**Review by td928 — COMMENTED** [review]
really like this proposal and we saw it working yesterday. One question I have about this is that from the title it suggests it is being automated but from what I understand it does not trigger an update automatically with a merge into main for example. I do want to clarify that if I have a misunderstanding about the use case. Secondly, the image tag is user generated and that's okay. I do wonder what convention we should establish going forward and formalize the process to make a new version like with an issue number system with the tag. Not really a feedback on this PR but really to bring up for broader discussion.

**Comment by SashaWeinstein** [comment]
Both great questions! 
If I understand you correctly on the "automate" wording question, you're saying that this doesn't fully automate the process because an engineer still has to press the workflow dispatch button. Which makes sense to me. I think this is more automated than typing in the commands to the CLI but we can save that term for when something is more fully integrated and the engineer doesn't have to think about it all.

I had an alternative idea for tag naming conventions. The idea is that don't let the user choose their own tag, and instead we have exactly two versions of the image on docker hub. One is latest and the other is staging. We have one action library archive that points to each. So the process to test a data library archive is to overwrite the staging image, call it with `NYCPlanning/action-library-archive@v1.1-test` or something like that, and if it works then tag the staging image as latest.

**Comment by SashaWeinstein** [comment]
Yea that's correct Te. This should make it easy to link an image with the version of data library that lives in it. I'll make the change to only allow two versions

**Comment by td928** [comment]
> Yea that's correct Te. This should make it easy to link an image with the version of data library that lives in it. I'll make the change to only allow two versions

I guess the only scenario this would cause trouble is where somehow our latest stopped working then by definition our staging is probably not working. As long as we can't fix staging/latest, we no longer have a recent working image. But from our experience working with docker image (the gdb exporting one for example), those image is rather resilient and would still work even long after the what they were built on is outdated for quite some time. So maybe my concern is invalid here.

**Comment by SashaWeinstein** [comment]
Also a good point! This approach does seem riskier. I think I'm ok with that though

**Review by td928 — APPROVED** [review]

**Pull request merged**
